### ISSUE TITLE
Not working when using with webpack

### ISSUE THREAD

**Issue by anhhnt** [dumbmatter/IndexedDB-getAll-shim#2]
Hi,

I have a case that the polyfill doesn't correctly patch when I use it with webpack.
I have a test case here. The problem is here :
`typeof window === "undefined" ? GLOBAL : this`
`this` doesn't point to window object 

Thanks for fixing this
[testcase.zip](https://github.com/dumbmatter/IndexedDB-getAll-shim/files/220345/testcase.zip)

**Comment by dumbmatter** [comment]
I don't know anything about webpack, so maybe you can help me debug... does it work if you change `this` to `window`? If so, I'll switch to that.

**Comment by anhhnt** [comment]
Yes, if there is no special reason to use `this` then we should switch to `window`. I confirm it works well.
Thank you very much.

**Comment by dumbmatter** [comment]
Thanks, I switched it and released v1.2.2.

I think I just copy/pasted that line from somewhere without thinking how weird it is to use `this` instead of `window`, damn cargo cult programming...
