### ISSUE TITLE
getAllKeys method on index return "index key" instead of "primary key"

### ISSUE THREAD

**Issue by youldali** [dumbmatter/IndexedDB-getAll-shim#3]
Hi,

When using your library, I noticed that the values returned by the getAllKeys method when used on an index returned the key of the records, instead of returning the primaryKey like it seems to be implemented on all modern browsers.

Let me know your thoughts

**Comment by dumbmatter** [comment]
Ahh I never actually used this feature personally, and my unit test was checking only for the number of keys returned, not the actual values!

Fixed in version 1.3.5.

Thanks!

**Comment by youldali** [comment]
Thank you for the quick fix :)
