### ISSUE TITLE
How to use this in an Angular app?

### ISSUE THREAD

**Issue by TheParad0X** [dumbmatter/IndexedDB-getAll-shim#5]
Hello,

Maybe I am blind, but I could not find how to use this with my angular app.

I did 
`yarn add indexeddb-getall-shim `

and then I imported it in my app.module:

`import "indexeddb-getall-shim";`

Is this supposed to be enough? I am still getting this error with Microsoft Edge 44.19041.1.0 when startiing my app:

![image](https://user-images.githubusercontent.com/17595640/89909031-e9d57000-dbee-11ea-8c5a-dc0ab44dac10.png)

Isn't this the error IndexedDB-getAll-shim is supposed to fix?
I also tried including it in the scripts part of my angular.json, but to no avail...

What am I missing?

Cheers

**Comment by dumbmatter** [comment]
Yeah, that should be enough. It won't do anything in recent versions of Edge though, because Edge already supports getAll. Not sure what SCRIPT1028 is in that error message.

**Comment by TheParad0X** [comment]
All right - we found the error. The problem was the import:

`import { DBSchema, deleteDB, openDB } from 'idb';
`

Internet Explorer 11 stops loading after this and the above error message shows because main.js (or vendor.js) is only partially loaded.

The solution was to import 'idb' dynamically, after checking if it is supported:

`  constructor() {
    if (isIdbSupported) {
      import('idb').then(idb => {
        this.deleteDB = idb.deleteDB;
        this.openDB = idb.openDB;
      });
    }
  }`

I'll leave this here, maybe someone is having the same problem :)
